package com.srn.erp.ventas.bl.Factory;

import com.srn.erp.general.bm.Idioma;
import com.srn.erp.general.bm.Moneda;
import com.srn.erp.general.bm.Pais;
import com.srn.erp.general.bm.Provincia;
import com.srn.erp.impuestos.bm.SujetoImpositivo;
import com.srn.erp.stock.bm.Transporte;
import com.srn.erp.tesoreria.bm.CuentaBancaria;
import com.srn.erp.tesoreria.bm.TarjetaCredito;
import com.srn.erp.turnos.bm.CategoriaSujetoTurno;
import com.srn.erp.turnos.bm.RelacionSujetoTurno;
import com.srn.erp.ventas.bm.Canal;
import com.srn.erp.ventas.bm.ClasifSujeto;
import com.srn.erp.ventas.bm.Cobrador;
import com.srn.erp.ventas.bm.CondicionPago;
import com.srn.erp.ventas.bm.EstadoCivil;
import com.srn.erp.ventas.bm.EstadoSituacion;
import com.srn.erp.ventas.bm.Rubro;
import com.srn.erp.ventas.bm.SectorDireccion;
import com.srn.erp.ventas.bm.Sujeto;
import com.srn.erp.ventas.bm.TipoDocumento;
import com.srn.erp.ventas.bm.Vendedor;
import com.srn.erp.ventas.bm.Zona;
import com.srn.erp.ventas.da.DBSujeto;

import framework.applicarionServer.bl.ObjetosAplicacion.FactoryObjetoLogico;
import framework.applicarionServer.bl.ObjetosAplicacion.IObjetoLogico;
import framework.applicarionServer.bl.Persistencia.IDBObjetoPersistente;
import framework.request.bl.Utils.BaseException;

public class FactorySujeto extends FactoryObjetoLogico {

  public FactorySujeto() {
  }

  public void cargarObjeto(IObjetoLogico objLog, IDBObjetoPersistente db) throws BaseException {
    Sujeto sujeto = (Sujeto) objLog;
    sujeto.setOID(db.getInteger(DBSujeto.OID_SUJETO));
    sujeto.setCodigo(db.getString(DBSujeto.CODIGO));
    sujeto.setRazon_social(db.getString(DBSujeto.RAZON_SOCIAL));
    sujeto.setTipo_documento(TipoDocumento.findByOidProxy(db.getInteger(DBSujeto.OID_TIPO_DOCUMENTO),getSesion()));
    sujeto.setNro_documento(db.getString(DBSujeto.NRO_DOCUMENTO));
    sujeto.setSexo(db.getString(DBSujeto.SEXO));
    sujeto.setFecha_nacimiento(db.getDate(DBSujeto.FEC_NAC));
    sujeto.setFecha_ingreso(db.getDate(DBSujeto.FEC_INGRESO));
    sujeto.setE_mail(db.getString(DBSujeto.E_MAIL));
    sujeto.setNacionalidad(db.getString(DBSujeto.NACIONALIDAD));
    sujeto.setTelefonos(db.getString(DBSujeto.TELEFONOS));
    sujeto.setSujeto_impositivo(SujetoImpositivo.findByOidProxy(db.getInteger(DBSujeto.OID_SUJ_IMP),getSesion()));
    sujeto.setFax(db.getString(DBSujeto.FAX));
    sujeto.setSector_empresa(db.getString(DBSujeto.SECTOR));
    sujeto.setCargo(db.getString(DBSujeto.CARGO));
    sujeto.setVendedor_tecnico(Vendedor.findByOidProxy(db.getInteger(DBSujeto.OID_VEND_TEC),getSesion()));
    sujeto.setVendedor_comercial(Vendedor.findByOidProxy(db.getInteger(DBSujeto.OID_VEND_COM),getSesion()));
    sujeto.setWeb(db.getString(DBSujeto.WEB));
    sujeto.setEstado_situacion(EstadoSituacion.findByOidProxy(db.getInteger(DBSujeto.OID_EST_SITUACION),getSesion()));
    sujeto.setZonadireccion(com.srn.erp.general.bm.Zona.findByOidProxy(db.getInteger(DBSujeto.OID_ZONA),getSesion()));
    sujeto.setFec_est_situ_desde(db.getDate(DBSujeto.FEC_EST_DESDE));
    sujeto.setFec_est_situ_hasta(db.getDate(DBSujeto.FEC_EST_HASTA));
    sujeto.setFisica_juridica(db.getString(DBSujeto.FISICA_JURIDICA));
    sujeto.setProfesion(db.getString(DBSujeto.PROFESION));
    sujeto.setEs_cliente(db.getBoolean(DBSujeto.ES_CLIENTE));
    sujeto.setEs_socio(db.getBoolean(DBSujeto.ES_SOCIO));
    sujeto.setDireccion_web(db.getString(DBSujeto.DIRECCION_WEB));
    sujeto.setCobrador(Cobrador.findByOidProxy(db.getInteger(DBSujeto.OID_COBRADOR),getSesion()));
    sujeto.setRubro(Rubro.findByOidProxy(db.getInteger(DBSujeto.OID_RUBRO),getSesion()));
    sujeto.setEstado_civil(EstadoCivil.findByOidProxy(db.getInteger(DBSujeto.OID_ESTADO_CIVIL),getSesion()));
    sujeto.setContacto(db.getString(DBSujeto.CONTACTO));
    sujeto.setCalle_y_nro(db.getString(DBSujeto.CALLE_Y_NRO));
    sujeto.setSector_domilicio(SectorDireccion.findByOidProxy(db.getInteger(DBSujeto.OID_SECTOR_DIR),getSesion()));
    sujeto.setLocalidad(db.getString(DBSujeto.LOCALIDAD));
    sujeto.setCodigo_postal(db.getString(DBSujeto.CODIGO_POSTAL));
    sujeto.setProvincia(Provincia.findByOidProxy(db.getInteger(DBSujeto.OID_PROVINCIA),getSesion()));
    sujeto.setPais(Pais.findByOidProxy(db.getInteger(DBSujeto.OID_PAIS),getSesion()));
    sujeto.setDomicilio_entrega(db.getBoolean(DBSujeto.DOM_ENTREGA));
    sujeto.setZona_venta(Zona.findByOidProxy(db.getInteger(DBSujeto.OID_ZONA_VTA),getSesion()));
    sujeto.setCanal(Canal.findByOidProxy(db.getInteger(DBSujeto.OID_CANAL),getSesion()));
    sujeto.setClasificacionsujeto(ClasifSujeto.findByOidProxy(db.getInteger(DBSujeto.OID_CLASIF_SUJETO),getSesion()));
    sujeto.setCuenta_bancaria(CuentaBancaria.findByOidProxy(db.getInteger(DBSujeto.OID_CTA_BANCARIA),getSesion()));
    sujeto.setTarjeta_credito(TarjetaCredito.findByOidProxy(db.getInteger(DBSujeto.OID_TAR_CREDITO),getSesion()));
    sujeto.setNro_medio_pago(db.getString(DBSujeto.NRO_MEDIO_PAGO));
    sujeto.setResponsable_ctacte(db.getInteger(DBSujeto.OID_SUJ_RESP_CC));	
    sujeto.setModalidad_pago(db.getString(DBSujeto.MODA_PAGO));
    sujeto.setPermite_otras_modalidades_pago(db.getBoolean(DBSujeto.PERMITE_OTRAS_MP));
    sujeto.setSub_modalidad_pago(db.getString(DBSujeto.SUB_MODA_PAGO));
    sujeto.setCondicionPago(CondicionPago.findByOidProxy(db.getInteger(DBSujeto.COND_PAGO),getSesion()));
    sujeto.setActivo(db.getBoolean(DBSujeto.ACTIVO));
    sujeto.addOidValorClasif(new Integer(1),db.getInteger(DBSujeto.OID_CLASIF_01));
    sujeto.addOidValorClasif(new Integer(2),db.getInteger(DBSujeto.OID_CLASIF_02));
    sujeto.addOidValorClasif(new Integer(3),db.getInteger(DBSujeto.OID_CLASIF_03));
    sujeto.addOidValorClasif(new Integer(4),db.getInteger(DBSujeto.OID_CLASIF_04));
    sujeto.addOidValorClasif(new Integer(5),db.getInteger(DBSujeto.OID_CLASIF_05));
    sujeto.addOidValorClasif(new Integer(6),db.getInteger(DBSujeto.OID_CLASIF_06));
    sujeto.addOidValorClasif(new Integer(7),db.getInteger(DBSujeto.OID_CLASIF_07));
    sujeto.addOidValorClasif(new Integer(8),db.getInteger(DBSujeto.OID_CLASIF_08));
    sujeto.addOidValorClasif(new Integer(9),db.getInteger(DBSujeto.OID_CLASIF_09));
    sujeto.addOidValorClasif(new Integer(10),db.getInteger(DBSujeto.OID_CLASIF_10));
    sujeto.addOidValorClasif(new Integer(11),db.getInteger(DBSujeto.OID_CLASIF_11));
    sujeto.addOidValorClasif(new Integer(12),db.getInteger(DBSujeto.OID_CLASIF_12));
    sujeto.addOidValorClasif(new Integer(13),db.getInteger(DBSujeto.OID_CLASIF_13));
    sujeto.addOidValorClasif(new Integer(14),db.getInteger(DBSujeto.OID_CLASIF_14));
    sujeto.addOidValorClasif(new Integer(15),db.getInteger(DBSujeto.OID_CLASIF_15));
    sujeto.addOidValorClasif(new Integer(16),db.getInteger(DBSujeto.OID_CLASIF_16));
    sujeto.addOidValorClasif(new Integer(17),db.getInteger(DBSujeto.OID_CLASIF_17));
    sujeto.addOidValorClasif(new Integer(18),db.getInteger(DBSujeto.OID_CLASIF_18));
    sujeto.addOidValorClasif(new Integer(19),db.getInteger(DBSujeto.OID_CLASIF_19));
    sujeto.addOidValorClasif(new Integer(20),db.getInteger(DBSujeto.OID_CLASIF_20));
    sujeto.setEs_contacto(db.getBoolean(DBSujeto.ES_CONTACTO));
    sujeto.setEs_prospecto(db.getBoolean(DBSujeto.ES_PROSPECTO));
    sujeto.setBonifEnCascada(db.getBoolean(DBSujeto.BONIF_EN_CASCADA));
    sujeto.setTransporte(Transporte.findByOidProxy(db.getInteger(DBSujeto.OID_TRANSPORTE),getSesion()));    
    sujeto.setMonedaCotizacion(Moneda.findByOidProxy(db.getInteger(DBSujeto.OID_MONEDA_COTIZACION),getSesion()));
    sujeto.setMonedaPedido(Moneda.findByOidProxy(db.getInteger(DBSujeto.OID_MONEDA_PEDIDO),getSesion()));
    sujeto.setMonedaFactura(Moneda.findByOidProxy(db.getInteger(DBSujeto.OID_MONEDA_FACTURA),getSesion()));
    sujeto.setIdioma(Idioma.findByOidProxy(db.getInteger(DBSujeto.OID_IDIOMA),getSesion()));
    sujeto.setHabilitarLimiteCredito(db.getBoolean(DBSujeto.HAB_LIM_CRE));
    sujeto.setMontoLimiteCredito(db.getMoney(DBSujeto.MONTO_LIM_CRE));
    sujeto.setMonedaLimiteCredito(Moneda.findByOidProxy(db.getInteger(DBSujeto.OID_MON_LIM_CRE),getSesion()));
    sujeto.setSusceptiblePercIBBsAs(db.getBoolean(DBSujeto.ES_SUS_PERC_IB_BA).booleanValue());
    sujeto.setSusceptiblePercIBCapFed(db.getBoolean(DBSujeto.ES_SUS_PERC_IB_CF).booleanValue());
    sujeto.setEsSusceptiblePercIVA(db.getBoolean(DBSujeto.ES_SUS_PERC_IVA).booleanValue());
    sujeto.setIsDomicilioCobranza(db.getBoolean(DBSujeto.DOM_COBRANZA));
    sujeto.setPasarACobrar(db.getString(DBSujeto.PASAR_A_COBRAR));
    sujeto.setReclamarPagos(db.getString(DBSujeto.RECLAMAR_PAGO));
    sujeto.setCategoriaSujetoTurno(CategoriaSujetoTurno.findByOidProxy(db.getInteger(DBSujeto.OID_TURNO_CATEG),getSesion()));
    sujeto.setRelacionSujetoTurno(RelacionSujetoTurno.findByOidProxy(db.getInteger(DBSujeto.OID_TURNO_RELACION),getSesion()));
    sujeto.setSuspendidoParaTurno(db.getBoolean(DBSujeto.SUSPEND_PARA_TURNO));
    sujeto.setFecSuspendidoDesde(db.getDate(DBSujeto.FEC_SUSP_DESDE));
    sujeto.setFecSuspendidoHasta(db.getDate(DBSujeto.FEC_SUSP_HASTA));
    sujeto.setMotivoTurnoSuspension(db.getString(DBSujeto.MOTIVO_TURNO_SUSP));
    sujeto.setNroTarjeta(db.getString(DBSujeto.NRO_TARJETA));
    sujeto.setTipoImpresionFact(db.getString(DBSujeto.TIPO_IMPRESION_FACT));
  }
}
