package com.srn.erp.presupuesto.bl.Factory;

import com.srn.erp.presupuesto.bm.RepositorioReal;
import com.srn.erp.presupuesto.bm.ValorCompoReal;
import com.srn.erp.presupuesto.bm.ValorRealRepositorio;
import com.srn.erp.presupuesto.da.DBValorRealRepositorio;

import framework.applicarionServer.bl.ObjetosAplicacion.FactoryObjetoLogico;
import framework.applicarionServer.bl.ObjetosAplicacion.IObjetoLogico;
import framework.applicarionServer.bl.Persistencia.IDBObjetoPersistente;
import framework.request.bl.Utils.BaseException;

public class FactoryValorRealRepositorio extends FactoryObjetoLogico { 

  public FactoryValorRealRepositorio() { 
  }

  public void cargarObjeto(IObjetoLogico objLog, IDBObjetoPersistente db) throws BaseException {
    ValorRealRepositorio valorrealrepositorio = (ValorRealRepositorio) objLog;
   valorrealrepositorio.setOID(db.getInteger(DBValorRealRepositorio.OID_VAL_REPO_REAL));
    valorrealrepositorio.setRepositorio_real(RepositorioReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_REPO_REAL),getSesion()));
    valorrealrepositorio.setValor_real_1(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_1),getSesion()));
    valorrealrepositorio.setValor_real_2(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_2),getSesion()));
    valorrealrepositorio.setValor_real_3(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_3),getSesion()));
    valorrealrepositorio.setValor_real_4(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_4),getSesion()));
    valorrealrepositorio.setValor_real_5(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_5),getSesion()));
    valorrealrepositorio.setValor_real_6(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_6),getSesion()));
    valorrealrepositorio.setValor_real_7(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_7),getSesion()));
    valorrealrepositorio.setValor_real_8(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_8),getSesion()));
    valorrealrepositorio.setValor_real_9(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_9),getSesion()));
    valorrealrepositorio.setValor_real_10(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_10),getSesion()));
    valorrealrepositorio.setValor_real_11(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_11),getSesion()));
    valorrealrepositorio.setValor_real_12(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_12),getSesion()));
    valorrealrepositorio.setValor_real_13(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_13),getSesion()));
    valorrealrepositorio.setValor_real_14(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_14),getSesion()));
    valorrealrepositorio.setValor_real_15(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_15),getSesion()));
    valorrealrepositorio.setValor_real_16(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_16),getSesion()));
    valorrealrepositorio.setValor_real_17(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_17),getSesion()));
    valorrealrepositorio.setValor_real_18(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_18),getSesion()));
    valorrealrepositorio.setValor_real_19(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_19),getSesion()));
    valorrealrepositorio.setValor_real_20(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_20),getSesion()));
    valorrealrepositorio.setValor_real_21(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_21),getSesion()));
    valorrealrepositorio.setValor_real_22(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_22),getSesion()));
    valorrealrepositorio.setValor_real_23(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_23),getSesion()));
    valorrealrepositorio.setValor_real_24(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_24),getSesion()));
    valorrealrepositorio.setValor_real_25(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_25),getSesion()));
    valorrealrepositorio.setValor_real_26(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_26),getSesion()));
    valorrealrepositorio.setValor_real_27(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_27),getSesion()));
    valorrealrepositorio.setValor_real_28(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_28),getSesion()));
    valorrealrepositorio.setValor_real_29(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_29),getSesion()));
    valorrealrepositorio.setValor_real_30(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_30),getSesion()));
    valorrealrepositorio.setValor_real_31(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_31),getSesion()));
    valorrealrepositorio.setValor_real_32(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_32),getSesion()));
    valorrealrepositorio.setValor_real_33(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_33),getSesion()));
    valorrealrepositorio.setValor_real_34(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_34),getSesion()));
    valorrealrepositorio.setValor_real_35(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_35),getSesion()));
    valorrealrepositorio.setValor_real_36(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_36),getSesion()));
    valorrealrepositorio.setValor_real_37(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_37),getSesion()));
    valorrealrepositorio.setValor_real_38(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_38),getSesion()));
    valorrealrepositorio.setValor_real_39(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_39),getSesion()));
    valorrealrepositorio.setValor_real_40(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_40),getSesion()));
    valorrealrepositorio.setValor_real_41(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_41),getSesion()));
    valorrealrepositorio.setValor_real_42(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_42),getSesion()));
    valorrealrepositorio.setValor_real_43(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_43),getSesion()));
    valorrealrepositorio.setValor_real_44(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_44),getSesion()));
    valorrealrepositorio.setValor_real_45(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_45),getSesion()));
    valorrealrepositorio.setValor_real_46(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_46),getSesion()));
    valorrealrepositorio.setValor_real_47(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_47),getSesion()));
    valorrealrepositorio.setValor_real_48(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_48),getSesion()));
    valorrealrepositorio.setValor_real_49(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_49),getSesion()));
    valorrealrepositorio.setValor_real_50(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_50),getSesion()));
    valorrealrepositorio.setValor_real_51(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_51),getSesion()));
    valorrealrepositorio.setValor_real_52(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_52),getSesion()));
    valorrealrepositorio.setValor_real_53(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_53),getSesion()));
    valorrealrepositorio.setValor_real_54(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_54),getSesion()));
    valorrealrepositorio.setValor_real_55(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_55),getSesion()));
    valorrealrepositorio.setValor_real_56(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_56),getSesion()));
    valorrealrepositorio.setValor_real_57(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_57),getSesion()));
    valorrealrepositorio.setValor_real_58(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_58),getSesion()));
    valorrealrepositorio.setValor_real_59(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_59),getSesion()));
    valorrealrepositorio.setValor_real_60(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_60),getSesion()));
    valorrealrepositorio.setValor_real_61(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_61),getSesion()));
    valorrealrepositorio.setValor_real_62(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_62),getSesion()));
    valorrealrepositorio.setValor_real_63(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_63),getSesion()));
    valorrealrepositorio.setValor_real_64(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_64),getSesion()));
    valorrealrepositorio.setValor_real_65(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_65),getSesion()));
    valorrealrepositorio.setValor_real_66(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_66),getSesion()));
    valorrealrepositorio.setValor_real_67(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_67),getSesion()));
    valorrealrepositorio.setValor_real_68(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_68),getSesion()));
    valorrealrepositorio.setValor_real_69(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_69),getSesion()));
    valorrealrepositorio.setValor_real_70(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_70),getSesion()));
    valorrealrepositorio.setValor_real_71(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_71),getSesion()));
    valorrealrepositorio.setValor_real_72(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_72),getSesion()));
    valorrealrepositorio.setValor_real_73(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_73),getSesion()));
    valorrealrepositorio.setValor_real_74(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_74),getSesion()));
    valorrealrepositorio.setValor_real_75(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_75),getSesion()));
    valorrealrepositorio.setValor_real_76(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_76),getSesion()));
    valorrealrepositorio.setValor_real_77(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_77),getSesion()));
    valorrealrepositorio.setValor_real_78(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_78),getSesion()));
    valorrealrepositorio.setValor_real_79(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_79),getSesion()));
    valorrealrepositorio.setValor_real_80(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_80),getSesion()));
    valorrealrepositorio.setValor_real_81(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_81),getSesion()));
    valorrealrepositorio.setValor_real_82(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_82),getSesion()));
    valorrealrepositorio.setValor_real_83(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_83),getSesion()));
    valorrealrepositorio.setValor_real_84(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_84),getSesion()));
    valorrealrepositorio.setValor_real_85(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_85),getSesion()));
    valorrealrepositorio.setValor_real_86(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_86),getSesion()));
    valorrealrepositorio.setValor_real_87(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_87),getSesion()));
    valorrealrepositorio.setValor_real_88(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_88),getSesion()));
    valorrealrepositorio.setValor_real_89(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_89),getSesion()));
    valorrealrepositorio.setValor_real_90(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_90),getSesion()));
    valorrealrepositorio.setValor_real_91(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_91),getSesion()));
    valorrealrepositorio.setValor_real_92(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_92),getSesion()));
    valorrealrepositorio.setValor_real_93(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_93),getSesion()));
    valorrealrepositorio.setValor_real_94(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_94),getSesion()));
    valorrealrepositorio.setValor_real_95(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_95),getSesion()));
    valorrealrepositorio.setValor_real_96(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_96),getSesion()));
    valorrealrepositorio.setValor_real_97(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_97),getSesion()));
    valorrealrepositorio.setValor_real_98(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_98),getSesion()));
    valorrealrepositorio.setValor_real_99(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_99),getSesion()));
    valorrealrepositorio.setValor_real_100(ValorCompoReal.findByOidProxy(db.getInteger(DBValorRealRepositorio.OID_VAL_REAL_100),getSesion()));
    valorrealrepositorio.setVal_metrica_1(db.getDouble(DBValorRealRepositorio.VAL_METRICA_1));
    valorrealrepositorio.setVal_metrica_2(db.getDouble(DBValorRealRepositorio.VAL_METRICA_2));
    valorrealrepositorio.setVal_metrica_3(db.getDouble(DBValorRealRepositorio.VAL_METRICA_3));
    valorrealrepositorio.setVal_metrica_4(db.getDouble(DBValorRealRepositorio.VAL_METRICA_4));
    valorrealrepositorio.setVal_metrica_5(db.getDouble(DBValorRealRepositorio.VAL_METRICA_5));
    valorrealrepositorio.setVal_metrica_6(db.getDouble(DBValorRealRepositorio.VAL_METRICA_6));
    valorrealrepositorio.setVal_metrica_7(db.getDouble(DBValorRealRepositorio.VAL_METRICA_7));
    valorrealrepositorio.setVal_metrica_8(db.getDouble(DBValorRealRepositorio.VAL_METRICA_8));
    valorrealrepositorio.setVal_metrica_9(db.getDouble(DBValorRealRepositorio.VAL_METRICA_9));
    valorrealrepositorio.setVal_metrica_10(db.getDouble(DBValorRealRepositorio.VAL_METRICA_10));
    valorrealrepositorio.setVal_metrica_11(db.getDouble(DBValorRealRepositorio.VAL_METRICA_11));
    valorrealrepositorio.setVal_metrica_12(db.getDouble(DBValorRealRepositorio.VAL_METRICA_12));
    valorrealrepositorio.setVal_metrica_13(db.getDouble(DBValorRealRepositorio.VAL_METRICA_13));
    valorrealrepositorio.setVal_metrica_14(db.getDouble(DBValorRealRepositorio.VAL_METRICA_14));
    valorrealrepositorio.setVal_metrica_15(db.getDouble(DBValorRealRepositorio.VAL_METRICA_15));
    valorrealrepositorio.setVal_metrica_16(db.getDouble(DBValorRealRepositorio.VAL_METRICA_16));
    valorrealrepositorio.setVal_metrica_17(db.getDouble(DBValorRealRepositorio.VAL_METRICA_17));
    valorrealrepositorio.setVal_metrica_18(db.getDouble(DBValorRealRepositorio.VAL_METRICA_18));
    valorrealrepositorio.setVal_metrica_19(db.getDouble(DBValorRealRepositorio.VAL_METRICA_19));
    valorrealrepositorio.setVal_metrica_20(db.getDouble(DBValorRealRepositorio.VAL_METRICA_20));
    valorrealrepositorio.setVal_metrica_21(db.getDouble(DBValorRealRepositorio.VAL_METRICA_21));
    valorrealrepositorio.setVal_metrica_22(db.getDouble(DBValorRealRepositorio.VAL_METRICA_22));
    valorrealrepositorio.setVal_metrica_23(db.getDouble(DBValorRealRepositorio.VAL_METRICA_23));
    valorrealrepositorio.setVal_metrica_24(db.getDouble(DBValorRealRepositorio.VAL_METRICA_24));
    valorrealrepositorio.setVal_metrica_25(db.getDouble(DBValorRealRepositorio.VAL_METRICA_25));
    valorrealrepositorio.setVal_metrica_26(db.getDouble(DBValorRealRepositorio.VAL_METRICA_26));
    valorrealrepositorio.setVal_metrica_27(db.getDouble(DBValorRealRepositorio.VAL_METRICA_27));
    valorrealrepositorio.setVal_metrica_28(db.getDouble(DBValorRealRepositorio.VAL_METRICA_28));
    valorrealrepositorio.setVal_metrica_29(db.getDouble(DBValorRealRepositorio.VAL_METRICA_29));
    valorrealrepositorio.setVal_metrica_30(db.getDouble(DBValorRealRepositorio.VAL_METRICA_30));
    valorrealrepositorio.setVal_metrica_31(db.getDouble(DBValorRealRepositorio.VAL_METRICA_31));
    valorrealrepositorio.setVal_metrica_32(db.getDouble(DBValorRealRepositorio.VAL_METRICA_32));
    valorrealrepositorio.setVal_metrica_33(db.getDouble(DBValorRealRepositorio.VAL_METRICA_33));
    valorrealrepositorio.setVal_metrica_34(db.getDouble(DBValorRealRepositorio.VAL_METRICA_34));
    valorrealrepositorio.setVal_metrica_35(db.getDouble(DBValorRealRepositorio.VAL_METRICA_35));
    valorrealrepositorio.setVal_metrica_36(db.getDouble(DBValorRealRepositorio.VAL_METRICA_36));
    valorrealrepositorio.setVal_metrica_37(db.getDouble(DBValorRealRepositorio.VAL_METRICA_37));
    valorrealrepositorio.setVal_metrica_38(db.getDouble(DBValorRealRepositorio.VAL_METRICA_38));
    valorrealrepositorio.setVal_metrica_39(db.getDouble(DBValorRealRepositorio.VAL_METRICA_39));
    valorrealrepositorio.setVal_metrica_40(db.getDouble(DBValorRealRepositorio.VAL_METRICA_40));
    valorrealrepositorio.setVal_metrica_41(db.getDouble(DBValorRealRepositorio.VAL_METRICA_41));
    valorrealrepositorio.setVal_metrica_42(db.getDouble(DBValorRealRepositorio.VAL_METRICA_42));
    valorrealrepositorio.setVal_metrica_43(db.getDouble(DBValorRealRepositorio.VAL_METRICA_43));
    valorrealrepositorio.setVal_metrica_44(db.getDouble(DBValorRealRepositorio.VAL_METRICA_44));
    valorrealrepositorio.setVal_metrica_45(db.getDouble(DBValorRealRepositorio.VAL_METRICA_45));
    valorrealrepositorio.setVal_metrica_46(db.getDouble(DBValorRealRepositorio.VAL_METRICA_46));
    valorrealrepositorio.setVal_metrica_47(db.getDouble(DBValorRealRepositorio.VAL_METRICA_47));
    valorrealrepositorio.setVal_metrica_48(db.getDouble(DBValorRealRepositorio.VAL_METRICA_48));
    valorrealrepositorio.setVal_metrica_49(db.getDouble(DBValorRealRepositorio.VAL_METRICA_49));
    valorrealrepositorio.setVal_metrica_50(db.getDouble(DBValorRealRepositorio.VAL_METRICA_50));
    valorrealrepositorio.setFec_tipo_peri_1(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_1));
    valorrealrepositorio.setFec_tipo_peri_2(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_2));
    valorrealrepositorio.setFec_tipo_peri_3(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_3));
    valorrealrepositorio.setFec_tipo_peri_4(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_4));
    valorrealrepositorio.setFec_tipo_peri_5(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_5));
    valorrealrepositorio.setFec_tipo_peri_6(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_6));
    valorrealrepositorio.setFec_tipo_peri_7(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_7));
    valorrealrepositorio.setFec_tipo_peri_8(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_8));
    valorrealrepositorio.setFec_tipo_peri_9(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_9));
    valorrealrepositorio.setFec_tipo_peri_10(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_10));
    valorrealrepositorio.setFec_tipo_peri_11(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_11));
    valorrealrepositorio.setFec_tipo_peri_12(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_12));
    valorrealrepositorio.setFec_tipo_peri_13(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_13));
    valorrealrepositorio.setFec_tipo_peri_14(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_14));
    valorrealrepositorio.setFec_tipo_peri_15(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_15));
    valorrealrepositorio.setFec_tipo_peri_16(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_16));
    valorrealrepositorio.setFec_tipo_peri_17(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_17));
    valorrealrepositorio.setFec_tipo_peri_18(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_18));
    valorrealrepositorio.setFec_tipo_peri_19(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_19));
    valorrealrepositorio.setFec_tipo_peri_20(db.getDate(DBValorRealRepositorio.FEC_TIPO_PERI_20));
    valorrealrepositorio.setActivo(db.getBoolean(DBValorRealRepositorio.ACTIVO));

  }
}
